---
abstract: 'A Task module for DWIM Perl L<http://dwimperl.com/>'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Perl::Version: 1.011
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-DWIM-OOP
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor: 0.34
  Class::Accessor::Chained: 0.01
  Class::Accessor::Grouped: 0.10006
  Class::Adapter: 1.08
  Class::Base: 0.04
  Class::MakeMethods: 1.01
  Class::Method::Modifiers: 1.12
  Class::Singleton: 1.4
  Class::XSAccessor: 1.13
  Object::Accessor: 0.42
  Object::Signature: 1.07
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dwimperl/Task-DWIM
version: 0.07
